version: '3.4'


services:
  zookeeper:
    image: debezium/zookeeper:1.6
    container_name: deb_zookeeper
    ports:
      - 2181:2181
      - 2888:2888 

  kafka:  
    image: debezium/kafka:1.6
    container_name: deb_kafka
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  connect:
    image: debezium/connect:1.6
    container_name: deb_connect
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"  

    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
      - db

  db:
    build:
     dockerfile:  Dockerfile.sqlserver
     context: .
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
      - MSSQL_AGENT_ENABLED=true

    ports:
      - '1433:1433' 

  api:  
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
     - 80:80 
    depends_on:
      - db   




  read:
    image: ${DOCKER_REGISTRY-}read
    build:
      context: .
      dockerfile: Read/Dockerfile
    depends_on:
      - db   
      - connect
      - kafka
